"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { formText, operationError, routeMessage } from "@/lib/actions/form";
import { getCurrentStaff } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
const path="/quality-campaigns";
async function run(call:(supabase:Awaited<ReturnType<typeof createClient>>)=>PromiseLike<{error:unknown}>,message:string,fallback:string){try{const supabase=await createClient();const {error}=await call(supabase);if(error)throw error;}catch(error){redirect(routeMessage(path,"error",operationError(error,fallback)));}revalidatePath(path);revalidatePath("/work-orders");redirect(routeMessage(path,"created",message));}
export async function recordQualityCheck(formData:FormData){await getCurrentStaff();const repairOrderId=formText(formData,"repairOrderId");const checklistVersion=formText(formData,"checklistVersion");const result=formText(formData,"result");if(!repairOrderId||!checklistVersion||!["pass","fail"].includes(result))redirect(routeMessage(path,"error","Repair order, checklist version and result are required."));return run(s=>s.rpc("record_quality_check",{p_repair_order_id:repairOrderId,p_job_id:formText(formData,"jobId")||null,p_checklist_version:checklistVersion,p_result:result,p_notes:formText(formData,"notes")}),"Quality check signed.","The quality check could not be signed.");}
export async function createCampaign(formData:FormData){const staff=await getCurrentStaff();const code=formText(formData,"code"),title=formText(formData,"title"),source=formText(formData,"sourceReference");if(!code||!title||!source)redirect(routeMessage(path,"error","Campaign code, title and authorized source are required."));return run(s=>s.rpc("create_service_campaign",{p_organization_id:staff.organizationId,p_code:code,p_title:title,p_description:formText(formData,"description"),p_source_reference:source}),"Advisory campaign created.","The campaign could not be created.");}
export async function transitionCampaign(formData:FormData){await getCurrentStaff();const id=formText(formData,"campaignId"),status=formText(formData,"status");if(!id||!["verified","retired"].includes(status))redirect(routeMessage(path,"error","Campaign transition is invalid."));return run(s=>s.rpc("transition_service_campaign",{p_campaign_id:id,p_to_status:status}),`Campaign ${status}.`,"The campaign could not be changed.");}
export async function matchVehicle(formData:FormData){await getCurrentStaff();const campaignId=formText(formData,"campaignId"),vehicleId=formText(formData,"vehicleId"),basis=formText(formData,"matchBasis");if(!campaignId||!vehicleId||!basis)redirect(routeMessage(path,"error","Campaign, vehicle and match basis are required."));return run(s=>s.rpc("match_vehicle_campaign",{p_campaign_id:campaignId,p_vehicle_id:vehicleId,p_match_basis:basis}),"Vehicle match recorded.","The vehicle could not be matched.");}
export async function transitionMatch(formData:FormData){await getCurrentStaff();const id=formText(formData,"matchId"),status=formText(formData,"status"),order=formText(formData,"repairOrderId")||null;if(!id||!["confirmed","completed","not_applicable"].includes(status))redirect(routeMessage(path,"error","Match transition is invalid."));return run(s=>s.rpc("transition_campaign_vehicle_match",{p_match_id:id,p_to_status:status,p_repair_order_id:order}),`Campaign match ${status.replace("_"," ")}.`,"The campaign match could not be changed.");}
