import { BadgeCheck, ClipboardCheck, Megaphone, ShieldAlert } from "lucide-react";
import { LabeledControl } from "@/components/labeled-control";
import { EmptyState } from "@/components/empty-state";
import { MetricStrip } from "@/components/metric-strip";
import { PageHeader } from "@/components/page-header";
import { RecordFeedback } from "@/components/record-feedback";
import { StatusPill } from "@/components/status-pill";
import { getCurrentStaff } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { createCampaign, matchVehicle, recordQualityCheck, transitionCampaign, transitionMatch } from "./actions";
type PageQuery={created?:string;error?:string}; const dt=new Intl.DateTimeFormat("en-JO",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Amman"});
export default async function QualityCampaignsPage({searchParams}:{searchParams:Promise<PageQuery>}){const query=await searchParams;const staff=await getCurrentStaff();const supabase=await createClient();const [{data:orders},{data:jobs},{data:checks,error},{data:profiles},{data:campaigns},{data:matches},{data:vehicles},{data:allOrders}]=await Promise.all([
 supabase.from("repair_orders").select("id,ro_number,status,branch:branches(code,city),vehicle:vehicles(id,registration_no,vin),customer:customers(display_name)").eq("organization_id",staff.organizationId).in("status",["qc","ready"]).order("opened_at",{ascending:false}),
 supabase.from("jobs").select("id,repair_order_id,description_snapshot,status").eq("organization_id",staff.organizationId),
 supabase.from("quality_checks").select("id,repair_order_id,job_id,checklist_version,result,notes,signed_by,signed_at,repair_order:repair_orders(ro_number),branch:branches(code,city)").eq("organization_id",staff.organizationId).order("signed_at",{ascending:false}),
 supabase.from("profiles").select("user_id,display_name"),
 supabase.from("service_campaigns").select("id,code,title,description,source_reference,status,verified_at,created_at").eq("organization_id",staff.organizationId).order("created_at",{ascending:false}),
 supabase.from("campaign_vehicle_matches").select("id,status,match_basis,vehicle_id,repair_order_id,campaign:service_campaigns(code,title),vehicle:vehicles(registration_no,vin,model:vehicle_models(name))").eq("organization_id",staff.organizationId).order("created_at",{ascending:false}),
 supabase.from("vehicles").select("id,registration_no,vin,model:vehicle_models(name)").eq("organization_id",staff.organizationId).eq("status","active").order("created_at",{ascending:false}).limit(200),
 supabase.from("repair_orders").select("id,ro_number,vehicle_id").eq("organization_id",staff.organizationId).order("opened_at",{ascending:false}).limit(200),
]);const names=new Map((profiles??[]).map(p=>[p.user_id,p.display_name]));
return <><PageHeader eyebrow="Release assurance" title="Quality & service campaigns" description="Require signed QC evidence before vehicle release and separate imported campaign hints from authorized VIN verification."/><RecordFeedback created={query.created} error={query.error??(error?"Quality records could not be loaded.":undefined)}/><MetricStrip metrics={[{label:"Awaiting QC",value:String((orders??[]).filter(o=>o.status==="qc").length),note:"Release blocked",icon:ClipboardCheck},{label:"QC failures",value:String((checks??[]).filter(c=>c.result==="fail").length),note:"Correction required",icon:ShieldAlert},{label:"Verified campaigns",value:String((campaigns??[]).filter(c=>c.status==="verified").length),note:"Authorized source",icon:BadgeCheck},{label:"Open matches",value:String((matches??[]).filter(m=>!["completed","not_applicable"].includes(m.status)).length),note:"VIN review queue",icon:Megaphone}]}/>
<div className="quality-grid"><section className="panel"><div className="panel-header"><div><div className="panel-title">Sign quality check</div><div className="panel-subtitle">The latest pass unlocks QC → Ready.</div></div></div><form action={recordQualityCheck} className="form-grid panel-body"><div className="form-field form-span-2"><label htmlFor="qc-order">Repair order</label><select id="qc-order" name="repairOrderId" required><option value="">Select QC order</option>{orders?.map(o=><option key={o.id} value={o.id}>{o.ro_number} · {o.vehicle?.registration_no??o.vehicle?.vin} · {o.branch?.city}</option>)}</select></div><div className="form-field"><label htmlFor="qc-job">Job (optional)</label><select id="qc-job" name="jobId"><option value="">Whole repair order</option>{jobs?.map(j=><option key={j.id} value={j.id}>{j.description_snapshot} · {j.status}</option>)}</select></div><div className="form-field"><label htmlFor="qc-version">Checklist version</label><input className="mono" id="qc-version" name="checklistVersion" defaultValue="VW-ID-QC-1" required/></div><div className="form-field"><label htmlFor="qc-result">Result</label><select id="qc-result" name="result" defaultValue="pass"><option value="pass">Pass</option><option value="fail">Fail</option></select></div><div className="form-field"><label htmlFor="qc-notes">Notes</label><input id="qc-notes" name="notes"/></div><div className="form-actions form-span-2"><button className="button primary" type="submit">Sign quality check</button></div></form></section>
<section className="panel"><div className="panel-header"><div><div className="panel-title">Create advisory campaign</div><div className="panel-subtitle">Verification is a separate accountable action.</div></div></div><form action={createCampaign} className="form-grid panel-body"><div className="form-field"><label htmlFor="campaign-code">Code</label><input className="mono" id="campaign-code" name="code" required/></div><div className="form-field"><label htmlFor="campaign-title">Title</label><input id="campaign-title" name="title" required/></div><div className="form-field form-span-2"><label htmlFor="campaign-source">Authorized source reference</label><input id="campaign-source" name="sourceReference" placeholder="Importer bulletin / authorized VIN list reference" required/></div><div className="form-field form-span-2"><label htmlFor="campaign-description">Description</label><textarea id="campaign-description" name="description"/></div><div className="form-actions form-span-2"><button className="button dark" type="submit">Create advisory</button></div></form></section></div>
<section className="panel"><div className="panel-header"><div><div className="panel-title">Campaign verification board</div><div className="panel-subtitle">A draft match never claims a vehicle is affected.</div></div></div><div className="campaign-board">{campaigns?.map(c=><article key={c.id}><div className="campaign-code mono">{c.code}</div><div><strong>{c.title}</strong><span>{c.source_reference}</span></div><StatusPill label={c.status} tone={c.status==="verified"?"green":c.status==="retired"?"gray":"amber"}/>{c.status==="draft"?<form action={transitionCampaign}><input type="hidden" name="campaignId" value={c.id}/><input type="hidden" name="status" value="verified"/><button className="button compact" type="submit">Verify source</button></form>:c.status==="verified"?<form action={transitionCampaign}><input type="hidden" name="campaignId" value={c.id}/><input type="hidden" name="status" value="retired"/><button className="button compact" type="submit">Retire</button></form>:null}</article>)}</div><form action={matchVehicle} className="campaign-match-form"><LabeledControl label="Campaign"><select name="campaignId" required><option value="">Campaign</option>{campaigns?.filter(c=>c.status!=="retired").map(c=><option key={c.id} value={c.id}>{c.code} · {c.title}</option>)}</select></LabeledControl><LabeledControl label="Vehicle"><select name="vehicleId" required><option value="">Vehicle</option>{vehicles?.map(v=><option key={v.id} value={v.id}>{v.model?.name??"Volkswagen ID"} · {v.registration_no??v.vin}</option>)}</select></LabeledControl><LabeledControl label="Match reference"><input name="matchBasis" placeholder="VIN list row / authorized lookup reference" required/></LabeledControl><button className="button primary" type="submit">Record match</button></form></section>
{!matches?.length?<EmptyState icon={Megaphone} title="No campaign vehicle matches" description="Record an advisory or verified match without claiming unsupported OEM status."/>:<section className="panel"><div className="panel-header"><div><div className="panel-title">Vehicle campaign register</div><div className="panel-subtitle">Completion requires a repair order for the matched vehicle.</div></div></div><div className="data-scroll"><table className="data-table"><thead><tr><th>Campaign</th><th>Vehicle</th><th>Basis</th><th>Status</th><th>Action</th></tr></thead><tbody>{matches.map(m=><tr key={m.id}><td><div className="cell-main mono">{m.campaign?.code}</div><div className="cell-sub">{m.campaign?.title}</div></td><td>{m.vehicle?.model?.name} · {m.vehicle?.registration_no??m.vehicle?.vin}</td><td>{m.match_basis}</td><td><StatusPill label={m.status} tone={m.status==="completed"?"green":m.status==="advisory"?"amber":"blue"}/></td><td>{!["completed","not_applicable"].includes(m.status)?<form action={transitionMatch} className="inline-action"><input type="hidden" name="matchId" value={m.id}/><LabeledControl label="Status"><select name="status" defaultValue={m.status==="advisory"?"confirmed":"completed"}><option value="confirmed">Confirm</option><option value="completed">Complete</option><option value="not_applicable">Not applicable</option></select></LabeledControl><LabeledControl label="Work order"><select name="repairOrderId" defaultValue=""><option value="">Repair order if completed</option>{allOrders?.filter(o=>o.vehicle_id===m.vehicle_id).map(o=><option key={o.id} value={o.id}>{o.ro_number}</option>)}</select></LabeledControl><button className="button compact" type="submit">Apply</button></form>:"—"}</td></tr>)}</tbody></table></div></section>}
<section className="panel"><div className="panel-header"><div><div className="panel-title">Signed QC ledger</div><div className="panel-subtitle">Append-only release evidence.</div></div></div><div className="data-scroll"><table className="data-table"><thead><tr><th>Work order</th><th>Checklist</th><th>Result</th><th>Signed by</th><th>Time</th><th>Notes</th></tr></thead><tbody>{checks?.length?checks.map(c=><tr key={c.id}><td className="mono">{c.repair_order?.ro_number}</td><td className="mono">{c.checklist_version}</td><td><StatusPill label={c.result} tone={c.result==="pass"?"green":"red"}/></td><td>{names.get(c.signed_by)??"Staff"}</td><td>{dt.format(new Date(c.signed_at))}</td><td>{c.notes??"—"}</td></tr>):<tr><td colSpan={6} className="table-empty">No quality checks signed.</td></tr>}</tbody></table></div></section></>}
