import Link from "next/link";
import { Activity, BatteryCharging, CheckCircle2, CircleGauge, Plus, ScanLine, TriangleAlert } from "lucide-react";
import { EmptyState } from "@/components/empty-state";
import { MetricStrip } from "@/components/metric-strip";
import { PageHeader } from "@/components/page-header";
import { RecordFeedback } from "@/components/record-feedback";
import { StatusPill } from "@/components/status-pill";
import { getCurrentStaff } from "@/lib/auth/session";
import type { Json } from "@/lib/database.types";
import { createClient } from "@/lib/supabase/server";
import { completeDiagnosticSession, recordBatteryHealth, recordDiagnosticCode, setDiagnosticCodeOutcome, startDiagnosticSession } from "./actions";

type PageQuery = { new?: "session" | "battery"; order?: string; session?: string; created?: string; error?: string };
type PillTone = "blue" | "green" | "amber" | "red" | "gray";
type Conditions = { ambient_temperature_c?: number | null; state_of_charge_percent?: number | null };

const dateTime = new Intl.DateTimeFormat("en-JO", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Amman" });
function tone(status: string | null): PillTone {
  if (["cleared", "completed", "passive"].includes(status ?? "")) return "green";
  if (["sporadic", "stored", "not_tested"].includes(status ?? "")) return "amber";
  if (["active", "returned"].includes(status ?? "")) return "red";
  return "blue";
}
function conditions(value: Json): Conditions {
  if (!value || typeof value !== "object" || Array.isArray(value)) return {};
  return {
    ambient_temperature_c: typeof value.ambient_temperature_c === "number" ? value.ambient_temperature_c : null,
    state_of_charge_percent: typeof value.state_of_charge_percent === "number" ? value.state_of_charge_percent : null,
  };
}

export default async function DiagnosticsPage({ searchParams }: { searchParams: Promise<PageQuery> }) {
  const query = await searchParams;
  const staff = await getCurrentStaff();
  const supabase = await createClient();
  const [{ data: orders }, { data: sessions, error }, { data: reports }, { data: technicians }] = await Promise.all([
    supabase.from("repair_orders").select("id, ro_number, status, branch:branches(code, city), customer:customers(display_name), vehicle:vehicles(id, vin, registration_no, battery_kwh, model:vehicle_models(name))").eq("organization_id", staff.organizationId).not("status", "in", '("closed","cancelled")').order("opened_at", { ascending: false }),
    supabase.from("diagnostic_sessions").select("id, repair_order_id, technician_id, tool, tool_version, interface_serial, external_ref, started_at, ended_at, branch:branches(code, city), repair_order:repair_orders(ro_number, customer:customers(display_name), vehicle:vehicles(id, vin, registration_no, battery_kwh, model:vehicle_models(name))), diagnostic_trouble_codes(id, control_unit, code, description_snapshot, before_status, after_status, created_at)").eq("organization_id", staff.organizationId).order("started_at", { ascending: false }),
    supabase.from("battery_health_reports").select("id, vehicle_id, repair_order_id, measured_at, soh_percent, usable_kwh, method, tool, conditions_json, branch:branches(code, city), repair_order:repair_orders(ro_number), vehicle:vehicles(vin, registration_no, battery_kwh, model:vehicle_models(name))").eq("organization_id", staff.organizationId).order("measured_at", { ascending: false }),
    supabase.from("technician_profiles").select("id, user_id, employee_no, labor_grade").eq("organization_id", staff.organizationId).eq("active", true),
  ]);
  const userIds = (technicians ?? []).map((item) => item.user_id);
  const { data: profiles } = userIds.length ? await supabase.from("profiles").select("user_id, display_name").in("user_id", userIds) : { data: [] };
  const profileByUser = new Map((profiles ?? []).map((profile) => [profile.user_id, profile.display_name]));
  const technicianById = new Map((technicians ?? []).map((technician) => [technician.id, technician]));
  const activeOrderIds = new Set((sessions ?? []).filter((session) => !session.ended_at).map((session) => session.repair_order_id));
  const eligibleOrders = (orders ?? []).filter((order) => !activeOrderIds.has(order.id));
  const selected = sessions?.find((session) => session.id === query.session);
  const latestReport = selected ? reports?.find((report) => report.vehicle_id === selected.repair_order?.vehicle?.id) : reports?.[0];
  const health = latestReport?.soh_percent ?? null;
  const filledCells = health === null ? 0 : Math.round((health / 100) * 12);
  const activeSessions = (sessions ?? []).filter((session) => !session.ended_at);
  const allCodes = (sessions ?? []).flatMap((session) => session.diagnostic_trouble_codes);
  const unresolvedCodes = allCodes.filter((code) => !code.after_status || ["active", "returned", "sporadic", "not_tested"].includes(code.after_status));
  const lowHealth = (reports ?? []).filter((report) => report.soh_percent !== null && report.soh_percent < 80);
  const showSessionForm = query.new === "session" && eligibleOrders.length > 0;
  const showBatteryForm = query.new === "battery" && Boolean(orders?.length);
  const selectedTechnician = selected ? technicianById.get(selected.technician_id ?? "") : undefined;

  return <>
    <PageHeader eyebrow="VW ID technical record" title="Diagnostics & battery health" description="Capture scan provenance, fault-code outcomes and repeatable high-voltage battery measurements for every branch.">
      {orders?.length ? <Link className="button" href="/diagnostics?new=battery#battery-report"><BatteryCharging /> Record battery health</Link> : null}
      {eligibleOrders.length ? <Link className="button primary" href="/diagnostics?new=session#new-diagnostic"><Plus /> Start diagnostic</Link> : null}
    </PageHeader>
    <RecordFeedback created={query.created} error={query.error ?? (error ? "Diagnostic records could not be loaded." : undefined)} />

    {showSessionForm ? <section className="panel operation-form diagnostic-form" id="new-diagnostic"><div className="panel-header"><div><div className="panel-title">Start guided diagnostic</div><div className="panel-subtitle">Record tool provenance; never enter ODIS or erWin credentials.</div></div><Link className="panel-link" href="/diagnostics">Cancel</Link></div><form action={startDiagnosticSession} className="form-grid panel-body"><div className="form-field form-span-2"><label htmlFor="diagnostic-order">Repair order</label><select id="diagnostic-order" name="repairOrderId" defaultValue={query.order ?? ""} required><option value="">Select repair order</option>{eligibleOrders.map((order) => <option key={order.id} value={order.id}>{order.ro_number} · {order.vehicle?.model?.name ?? "Volkswagen ID"} {order.vehicle?.registration_no ?? order.vehicle?.vin} · {order.branch?.city}</option>)}</select></div><div className="form-field"><label htmlFor="diagnostic-tool">Diagnostic tool</label><input id="diagnostic-tool" name="tool" placeholder="ODIS Service" required /></div><div className="form-field"><label htmlFor="diagnostic-version">Tool version</label><input className="mono" id="diagnostic-version" name="toolVersion" /></div><div className="form-field"><label htmlFor="diagnostic-interface">Interface serial</label><input className="mono" id="diagnostic-interface" name="interfaceSerial" /></div><div className="form-field"><label htmlFor="diagnostic-external">External session reference</label><input className="mono" id="diagnostic-external" name="externalRef" /></div><div className="form-field"><label htmlFor="diagnostic-start">Started at</label><input id="diagnostic-start" name="startedAt" type="datetime-local" required /></div><div className="form-actions form-span-2"><button className="button primary" type="submit">Start diagnostic session</button></div></form></section> : null}

    {showBatteryForm ? <section className="panel operation-form battery-form" id="battery-report"><div className="panel-header"><div><div className="panel-title">Record battery-health measurement</div><div className="panel-subtitle">Use a repeatable method and preserve measurement conditions.</div></div><Link className="panel-link" href="/diagnostics">Cancel</Link></div><form action={recordBatteryHealth} className="form-grid panel-body"><div className="form-field form-span-2"><label htmlFor="battery-order">Repair order and vehicle</label><select id="battery-order" name="repairOrderId" defaultValue={query.order ?? ""} required><option value="">Select repair order</option>{orders?.map((order) => <option key={order.id} value={order.id}>{order.ro_number} · {order.vehicle?.model?.name ?? "Volkswagen ID"} · {order.vehicle?.registration_no ?? order.vehicle?.vin} · nominal {order.vehicle?.battery_kwh ?? "—"} kWh</option>)}</select></div><div className="form-field"><label htmlFor="battery-soh">State of health (%)</label><input id="battery-soh" name="sohPercent" type="number" min="0" max="100" step="0.01" /></div><div className="form-field"><label htmlFor="battery-usable">Usable energy (kWh)</label><input id="battery-usable" name="usableKwh" type="number" min="0" step="0.001" /></div><div className="form-field"><label htmlFor="battery-method">Measurement method</label><input id="battery-method" name="method" placeholder="ODIS guided function / capacity test" required /></div><div className="form-field"><label htmlFor="battery-tool">Tool</label><input id="battery-tool" name="tool" placeholder="ODIS Service" /></div><div className="form-field"><label htmlFor="battery-time">Measured at</label><input id="battery-time" name="measuredAt" type="datetime-local" required /></div><div className="form-field"><label htmlFor="battery-soc">State of charge (%)</label><input id="battery-soc" name="stateOfCharge" type="number" min="0" max="100" step="0.1" /></div><div className="form-field"><label htmlFor="battery-temperature">Ambient temperature (°C)</label><input id="battery-temperature" name="ambientTemperature" type="number" min="-40" max="80" step="0.1" /></div><div className="form-actions form-span-2"><button className="button primary" type="submit">Record battery report</button></div></form></section> : null}

    <MetricStrip metrics={[
      { label: "Active scans", value: String(activeSessions.length), note: "Open technician sessions", noteTone: activeSessions.length ? "warn" : "good", icon: ScanLine },
      { label: "Unresolved DTCs", value: String(unresolvedCodes.length), note: `${allCodes.length} total observations`, noteTone: unresolvedCodes.length ? "warn" : "good", icon: TriangleAlert },
      { label: "Battery reports", value: String(reports?.length ?? 0), note: "Longitudinal health record", icon: BatteryCharging },
      { label: "Below 80% SoH", value: String(lowHealth.length), note: "Requires customer review", noteTone: lowHealth.length ? "warn" : "good", icon: CircleGauge },
    ]} />

    {selected ? <section className="diagnostic-workspace" id="diagnostic-workspace"><div className="diagnostic-hero"><div><span>{selected.branch?.city} · {selected.repair_order?.ro_number}</span><h2>{selected.repair_order?.vehicle?.model?.name ?? "Volkswagen ID"} <small>{selected.repair_order?.vehicle?.registration_no ?? selected.repair_order?.vehicle?.vin}</small></h2><p>{selected.tool}{selected.tool_version ? ` ${selected.tool_version}` : ""} · {selectedTechnician ? profileByUser.get(selectedTechnician.user_id) ?? selectedTechnician.employee_no : "Technician"} · {dateTime.format(new Date(selected.started_at))}</p></div><StatusPill label={selected.ended_at ? "completed" : "active scan"} tone={selected.ended_at ? "green" : "blue"} /></div>
      <div className="battery-cell-band"><div className="battery-cell-label"><BatteryCharging /><div><strong>{health === null ? "No battery baseline" : `${health.toFixed(1)}% SoH`}</strong><span>{latestReport ? `${latestReport.usable_kwh ?? "—"} kWh usable · ${latestReport.method}` : "Record a repeatable health measurement"}</span></div></div><div className={`battery-cells ${health !== null && health < 80 ? "low" : ""}`} aria-label={health === null ? "No state of health recorded" : `${health}% state of health`}>{Array.from({ length: 12 }, (_, index) => <i className={index < filledCells ? "filled" : ""} key={index} />)}</div></div>
      <div className="diagnostic-columns"><div className="stack"><section className="panel"><div className="panel-header"><div><div className="panel-title">Diagnostic trouble codes</div><div className="panel-subtitle">Before/after evidence from one immutable scan session.</div></div>{!selected.ended_at ? <form action={completeDiagnosticSession}><input type="hidden" name="sessionId" value={selected.id} /><button className="button dark" type="submit"><CheckCircle2 /> Complete and lock</button></form> : null}</div>
        {!selected.ended_at ? <form action={recordDiagnosticCode} className="dtc-entry panel-body"><input type="hidden" name="sessionId" value={selected.id} /><div className="form-field"><label htmlFor="dtc-unit">Control unit</label><input className="mono" id="dtc-unit" name="controlUnit" placeholder="8C · HV battery management" required /></div><div className="form-field"><label htmlFor="dtc-code">DTC</label><input className="mono" id="dtc-code" name="code" placeholder="P0A80" required /></div><div className="form-field"><label htmlFor="dtc-status">Initial status</label><select id="dtc-status" name="beforeStatus" defaultValue="active"><option value="active">Active</option><option value="sporadic">Sporadic</option><option value="stored">Stored</option><option value="passive">Passive</option><option value="unknown">Unknown</option></select></div><div className="form-field"><label htmlFor="dtc-description">Description</label><input id="dtc-description" name="description" placeholder="Snapshot from approved diagnostic source" /></div><div className="form-actions form-span-2"><button className="button primary" type="submit">Record DTC</button></div></form> : null}
        <div className="dtc-ledger">{selected.diagnostic_trouble_codes.length ? selected.diagnostic_trouble_codes.map((code) => <article key={code.id}><div className="dtc-code mono">{code.code}</div><div><strong>{code.control_unit}</strong><span>{code.description_snapshot ?? "No description recorded"}</span></div><div className="dtc-state"><StatusPill label={code.before_status ?? "unknown"} tone={tone(code.before_status)} /><span>→</span><StatusPill label={code.after_status ?? "pending"} tone={tone(code.after_status)} /></div>{!selected.ended_at ? <form action={setDiagnosticCodeOutcome}><input type="hidden" name="sessionId" value={selected.id} /><input type="hidden" name="troubleCodeId" value={code.id} /><select name="afterStatus" defaultValue={code.after_status ?? "not_tested"} aria-label={`Outcome for ${code.code}`}><option value="not_tested">Not tested</option><option value="cleared">Cleared</option><option value="active">Active</option><option value="sporadic">Sporadic</option><option value="returned">Returned</option></select><button className="button compact" type="submit">Save</button></form> : null}</article>) : <div className="table-empty">No DTCs recorded. A clean scan may be completed with zero codes.</div>}</div></section></div>
        <aside className="stack"><section className="panel diagnostic-facts"><div className="panel-header"><div><div className="panel-title">Scan provenance</div><div className="panel-subtitle">References only; no external credentials</div></div></div><dl><div><dt>Tool</dt><dd>{selected.tool}</dd></div><div><dt>Version</dt><dd className="mono">{selected.tool_version ?? "—"}</dd></div><div><dt>Interface</dt><dd className="mono">{selected.interface_serial ?? "—"}</dd></div><div><dt>External ref</dt><dd className="mono">{selected.external_ref ?? "—"}</dd></div><div><dt>Completed</dt><dd>{selected.ended_at ? dateTime.format(new Date(selected.ended_at)) : "Session active"}</dd></div></dl></section><section className="panel"><div className="panel-header"><div><div className="panel-title">Battery history</div><div className="panel-subtitle">Latest measurements for this vehicle</div></div></div><div className="battery-history">{(reports ?? []).filter((report) => report.vehicle_id === selected.repair_order?.vehicle?.id).slice(0, 5).map((report) => { const context = conditions(report.conditions_json); return <article key={report.id}><div><strong>{report.soh_percent === null ? "—" : `${report.soh_percent}%`} SoH</strong><span>{dateTime.format(new Date(report.measured_at))} · {context.state_of_charge_percent ?? "—"}% charge · {context.ambient_temperature_c ?? "—"}°C</span></div><b>{report.usable_kwh ?? "—"} kWh</b></article>; })}</div></section></aside></div>
    </section> : null}

    {!sessions?.length ? <EmptyState icon={Activity} title="No diagnostic sessions" description={orders?.length ? "Start a technician-owned scan session for an active repair order." : "Open a repair order before capturing diagnostic evidence."} action={eligibleOrders.length ? <Link className="button primary" href="/diagnostics?new=session#new-diagnostic">Start first diagnostic</Link> : undefined} /> : <section className="panel"><div className="panel-header"><div><div className="panel-title">Diagnostic session register</div><div className="panel-subtitle">Tool and DTC history across accessible branches.</div></div></div><div className="data-scroll"><table className="data-table diagnostic-table"><thead><tr><th>Work order</th><th>Vehicle & customer</th><th>Tool</th><th>Technician</th><th>DTCs</th><th>Status</th><th></th></tr></thead><tbody>{sessions.map((session) => { const technician = technicianById.get(session.technician_id ?? ""); return <tr key={session.id}><td><div className="cell-main mono">{session.repair_order?.ro_number}</div><div className="cell-sub">{dateTime.format(new Date(session.started_at))}</div></td><td><div className="cell-main">{session.repair_order?.vehicle?.model?.name ?? "Volkswagen ID"} · {session.repair_order?.vehicle?.registration_no ?? session.repair_order?.vehicle?.vin}</div><div className="cell-sub">{session.repair_order?.customer?.display_name}</div></td><td><div className="cell-main">{session.tool}</div><div className="cell-sub mono">{session.interface_serial ?? session.tool_version ?? "—"}</div></td><td>{technician ? profileByUser.get(technician.user_id) ?? technician.employee_no : "—"}</td><td className="mono">{session.diagnostic_trouble_codes.length}</td><td><StatusPill label={session.ended_at ? "completed" : "active"} tone={session.ended_at ? "green" : "blue"} /></td><td><Link className="button compact" href={`/diagnostics?session=${session.id}#diagnostic-workspace`}>Open</Link></td></tr>; })}</tbody></table></div></section>}
  </>;
}
