import { Activity, CloudCog, FileClock, PlugZap, ShieldCheck, TriangleAlert } from "lucide-react";
import { EmptyState } from "@/components/empty-state";
import { MetricStrip } from "@/components/metric-strip";
import { PageHeader } from "@/components/page-header";
import { StatusPill } from "@/components/status-pill";
import { getCurrentStaff } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
type Overview={connections:Array<{provider:string;status:string;configured:boolean;updated_at:string}>;outbox:Array<{event_type:string;pending:number;oldest_at:string|null}>;e_invoice:Array<{state:string;count:number}>;invalid_webhooks:number};
const adapters=[{provider:"jofotara",label:"Jordan e-invoicing",gate:"Tax sandbox credentials + accountant-certified UBL examples"},{provider:"messaging",label:"SMS / WhatsApp / email",gate:"Contracted provider + approved templates"},{provider:"payments",label:"Payment gateway",gate:"Provider credentials + signed webhook contract"},{provider:"volkswagen",label:"Volkswagen systems",gate:"Importer/OEM licensed API and technician authorization"},{provider:"malware_scan",label:"Evidence malware scan",gate:"Scanning provider + quarantine policy"}];const dt=new Intl.DateTimeFormat("en-JO",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Amman"});
export default async function GovernancePage(){const staff=await getCurrentStaff();const supabase=await createClient();const [{data:overviewData,error:integrationError},{data:audit,error:auditError}]=await Promise.all([supabase.rpc("integration_overview",{p_organization_id:staff.organizationId}),supabase.rpc("audit_recent",{p_organization_id:staff.organizationId,p_limit:150})]);const overview=(overviewData??{connections:[],outbox:[],e_invoice:[],invalid_webhooks:0}) as unknown as Overview;const byProvider=new Map(overview.connections.map(c=>[c.provider,c]));const pending=overview.outbox.reduce((sum,item)=>sum+Number(item.pending),0);const oldest=overview.outbox.map(item=>item.oldest_at).filter(Boolean).sort()[0];
return <><PageHeader eyebrow="Private-schema observability" title="Integrations & audit" description="See queues, adapter readiness and append-only activity without exposing secret references or provider payloads."/><MetricStrip metrics={[{label:"Configured adapters",value:String(overview.connections.filter(c=>c.configured&&c.status==="active").length),note:`${adapters.length} production boundaries`,icon:PlugZap},{label:"Pending events",value:String(pending),note:oldest?`Oldest ${dt.format(new Date(oldest))}`:"Queue clear",noteTone:pending?"warn":"good",icon:Activity},{label:"E-invoice rejections",value:String(overview.e_invoice.find(i=>i.state==="rejected")?.count??0),note:"Authoritative business state",icon:TriangleAlert},{label:"Audit events",value:String(audit?.length??0),note:"Latest redacted activity",icon:FileClock}]}/>
{integrationError?<EmptyState icon={ShieldCheck} title="Integration status is restricted" description="The integration.manage capability is required."/>:<section className="integration-radar">{adapters.map(adapter=>{const connection=byProvider.get(adapter.provider);return <article key={adapter.provider}><div className="integration-icon"><CloudCog/></div><div><span>{adapter.provider}</span><h2>{adapter.label}</h2><p>{adapter.gate}</p></div><StatusPill label={connection?.status??"external gate"} tone={connection?.status==="active"?"green":connection?.status==="error"?"red":"amber"}/><small>{connection?.configured?"Secret reference present":"No secret reference exposed"}</small></article>})}</section>}
<section className="panel"><div className="panel-header"><div><div className="panel-title">Transactional outbox</div><div className="panel-subtitle">Business writes remain committed while external providers retry independently.</div></div></div><div className="data-scroll"><table className="data-table"><thead><tr><th>Event type</th><th>Pending</th><th>Oldest pending</th></tr></thead><tbody>{overview.outbox.length?overview.outbox.map(item=><tr key={item.event_type}><td className="mono">{item.event_type}</td><td>{item.pending}</td><td>{item.oldest_at?dt.format(new Date(item.oldest_at)):"—"}</td></tr>):<tr><td colSpan={3} className="table-empty">No outbox events.</td></tr>}</tbody></table></div></section>
{auditError?<EmptyState icon={ShieldCheck} title="Audit history is restricted" description="The audit.read capability is required."/>:<section className="panel"><div className="panel-header"><div><div className="panel-title">Recent audit history</div><div className="panel-subtitle">Metadata and sensitive payloads remain private.</div></div></div><div className="data-scroll"><table className="data-table"><thead><tr><th>Time</th><th>Action</th><th>Entity</th><th>Identifier</th><th>Actor</th></tr></thead><tbody>{audit?.length?audit.map(item=><tr key={item.id}><td>{dt.format(new Date(item.occurred_at))}</td><td className="mono">{item.action}</td><td>{item.entity_type}</td><td className="mono">{item.entity_id?.slice(0,8)??"—"}</td><td>{item.actor_name??"System"}</td></tr>):<tr><td colSpan={5} className="table-empty">No audit events.</td></tr>}</tbody></table></div></section>}</>}
