import Link from "next/link";
import { BatteryCharging, CarFront, Gauge, History, Plus, ReceiptText, ShieldCheck, UserRoundCheck, Wrench } from "lucide-react";
import { BranchField } from "@/components/branch-field";
import { EmptyState } from "@/components/empty-state";
import { CustomerConcernText } from "@/components/customer-concern-text";
import { MetricStrip } from "@/components/metric-strip";
import { PageHeader } from "@/components/page-header";
import { RecordFeedback } from "@/components/record-feedback";
import { RecordFilters } from "@/components/record-filters";
import { matchesRecordSearch } from "@/lib/record-search";
import { RecordDocuments } from "@/components/record-documents";
import { CustomerServiceHistory } from "@/components/customer-service-history";
import { StatusPill } from "@/components/status-pill";
import { getCurrentStaff } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { addVehicleOwnership, completeVehicleIdentity, createRecommendation, createVehicle, endVehicleOwnership, recordOdometerReading, transitionRecommendation, updateVehicleProfile } from "./actions";

type PageQuery = { q?: string; filter?: string; customer?: string; new?: string; manage?: string; tab?: string; created?: string; error?: string };
type VehicleTab = "profile" | "odometer" | "ownership" | "service" | "quotes" | "invoices" | "documents";
type PillTone = "blue" | "green" | "amber" | "red" | "gray";

const serviceDate = new Intl.DateTimeFormat("en-JO", { dateStyle: "medium", timeZone: "Asia/Amman" });
const serviceMoney = new Intl.NumberFormat("en-JO", { style: "currency", currency: "JOD" });

function serviceTone(status: string): PillTone {
  if (["closed", "delivered", "completed", "paid"].includes(status)) return "green";
  if (["cancelled", "dismissed"].includes(status)) return "gray";
  if (["on_hold", "blocked", "awaiting_approval", "partially_paid"].includes(status)) return "amber";
  return "blue";
}

export default async function VehiclesPage({ searchParams }: { searchParams: Promise<PageQuery> }) {
  const query = await searchParams;
  const staff = await getCurrentStaff();
  const supabase = await createClient();
  const [{ data: branches }, { data: customers }, { data: models }, { data: vehicles, error }, { data: recommendations }] = await Promise.all([
    supabase.from("branches").select("id, code, city").eq("organization_id", staff.organizationId).eq("status", "active").order("city"),
    supabase.from("customers").select("id, display_name").eq("organization_id", staff.organizationId).eq("status", "active").order("display_name"),
    supabase.from("vehicle_models").select("id, name, model_code").or(`organization_id.is.null,organization_id.eq.${staff.organizationId}`).order("name"),
    supabase
      .from("vehicles")
      .select("id, vin, registration_no, model_year, trim, color, battery_kwh, drive_unit, connectivity_status, software_version, first_registration_date, primary_branch_id, status, model:vehicle_models(name), vehicle_ownerships(id, relationship, valid_from, valid_to, verified_at, customer:customers(id, display_name)), odometer_readings(reading_km, source, correction_reason, recorded_at, branch:branches(code, city)), battery_health_reports(soh_percent, measured_at)")
      .eq("organization_id", staff.organizationId)
      .order("created_at", { ascending: false }),
    supabase.from("vehicle_recommendations").select("id, vehicle_id, branch_id, description, severity, status, due_date, due_odometer_km, created_at, vehicle:vehicles(registration_no, vin, model:vehicle_models(name)), branch:branches(code, city)").eq("organization_id", staff.organizationId).order("created_at", { ascending: false }),
  ]);

  const visibleVehicles = (vehicles ?? []).filter(vehicle => (!query.filter || vehicle.status === query.filter) &&
    matchesRecordSearch(query.q, [vehicle.vin, vehicle.registration_no, vehicle.model?.name, vehicle.color, ...vehicle.vehicle_ownerships.map(o => o.customer?.display_name)]));
  const latestSoh = (vehicles ?? []).flatMap((vehicle) => vehicle.battery_health_reports.map((report) => report.soh_percent).filter((value): value is number => value !== null));
  const averageSoh = latestSoh.length ? latestSoh.reduce((sum, value) => sum + Number(value), 0) / latestSoh.length : null;
  const quarantined = (vehicles ?? []).filter((vehicle) => vehicle.status === "quarantine").length;
  const openRecommendations = (recommendations ?? []).filter((item) => item.status === "open" || item.status === "scheduled");
  const safetyAlerts = openRecommendations.filter((item) => item.severity === "red" || item.severity === "safety_stop").length;
  const setupReady = Boolean(branches?.length && customers?.length && models?.length);
  const showForm = query.new === "1" || Boolean(query.error && !query.manage);
  const managedVehicle = vehicles?.find((vehicle) => vehicle.id === query.manage);
  const { data: serviceHistory, error: serviceHistoryError } = managedVehicle ? await supabase
    .from("repair_orders")
    .select("id, ro_number, status, risk_state, opened_at, closed_at, odometer_km, customer_concern, branch:branches(code, city), customer:customers(display_name), jobs(id, description_snapshot, operation_code, status, safety_class, started_at, completed_at), invoices(id, invoice_number, status, currency, grand_total, paid_total, posted_at)")
    .eq("organization_id", staff.organizationId)
    .eq("vehicle_id", managedVehicle.id)
    .order("opened_at", { ascending: false }) : { data: [], error: null };
  const activeVehicleTab: VehicleTab = query.tab === "quotes" || query.tab === "invoices" || query.tab === "documents" || query.tab === "odometer" || query.tab === "ownership" || query.tab === "service" ? query.tab : "profile";
  const today = new Date().toISOString().slice(0, 10);

  return <>
    <PageHeader eyebrow="Vehicle registry" title="VW ID vehicles" description="VIN-led service history, ownership, odometer, battery health and technical diagnostics.">
      {vehicles?.length && branches?.length ? <Link className="button" href="/vehicles?new=recommendation#new-recommendation"><Plus /> Add deferred work</Link> : null}{setupReady ? <Link className="button primary" href="/vehicles?new=1#new-vehicle"><Plus /> Register vehicle</Link> : <Link className="button primary" href={branches?.length ? "/customers?new=1#new-customer" : "/branches?new=1#new-branch"}><Plus /> Complete setup</Link>}
    </PageHeader>
    <RecordFeedback created={query.created} error={query.error ?? (error || serviceHistoryError ? "Vehicle records could not be loaded." : undefined)} />

    {showForm && setupReady ? <section className="panel operation-form" id="new-vehicle">
      <div className="panel-header"><div><div className="panel-title">Register a VW ID vehicle</div><div className="panel-subtitle">Creates the vehicle, ownership link and initial odometer reading together.</div></div><Link className="panel-link" href="/vehicles">Cancel</Link></div>
      <form action={createVehicle} className="form-grid panel-body">
        <BranchField id="vehicle-branch" label="Intake branch" branches={branches} selectedBranchId={staff.selectedBranchId} value={branches?.length === 1 ? branches[0].id : undefined} />
        <div className="form-field"><label htmlFor="vehicle-customer">Owner</label><select id="vehicle-customer" name="customerId" defaultValue={customers?.some(c => c.id === query.customer) ? query.customer : ""} required><option value="">Select customer</option>{customers?.map((customer) => <option key={customer.id} value={customer.id}>{customer.display_name}</option>)}</select></div>
        <div className="form-field"><label htmlFor="vehicle-model">VW ID model</label><select id="vehicle-model" name="modelId" required><option value="">Select model</option>{models?.map((model) => <option key={model.id} value={model.id}>{model.name} · {model.model_code}</option>)}</select></div>
        <div className="form-field"><label htmlFor="vehicle-year">Model year</label><input id="vehicle-year" name="modelYear" type="number" min="2019" max={new Date().getFullYear() + 1} /></div>
        <div className="form-field form-span-2"><label htmlFor="vehicle-vin">VIN number</label><input className="mono" id="vehicle-vin" name="vin" minLength={17} maxLength={17} pattern="[A-HJ-NPR-Za-hj-npr-z0-9]{17}" placeholder="WVWZZZE1ZNP012418" dir="ltr" /></div>
        <div className="form-field"><label htmlFor="vehicle-registration">Registration number</label><input id="vehicle-registration" name="registrationNo" maxLength={40} dir="ltr" /></div>
        <p className="field-help form-span-2">Enter the plate or VIN. You can complete the missing identifier later.</p>
        <details className="journey-details form-span-2"><summary>Additional details (optional)</summary><div className="form-grid">
        <div className="form-field"><label htmlFor="vehicle-color">Vehicle color</label><input id="vehicle-color" name="color" maxLength={80} placeholder="e.g. Moonstone Grey" /></div>
        <div className="form-field"><label htmlFor="vehicle-trim">Trim</label><input id="vehicle-trim" name="trim" placeholder="Pro Performance" /></div>
        <div className="form-field"><label htmlFor="vehicle-battery">Battery capacity (kWh)</label><input id="vehicle-battery" name="batteryKwh" type="number" min="1" step="0.01" /></div>
        <div className="form-field"><label htmlFor="vehicle-odometer">Odometer (km)</label><input id="vehicle-odometer" name="odometerKm" type="number" min="0" step="1" /></div>
        </div></details>
        <div className="form-actions form-span-2"><Link className="button" href="/vehicles">Cancel</Link><button className="button primary" type="submit">Register vehicle</button></div>
      </form>
    </section> : null}

    {query.new === "recommendation" && vehicles?.length && branches?.length ? <section className="panel operation-form recommendation-form" id="new-recommendation"><div className="panel-header"><div><div className="panel-title">Record deferred work</div><div className="panel-subtitle">Keep declined or future work visible across every city visit.</div></div><Link className="panel-link" href="/vehicles">Cancel</Link></div><form action={createRecommendation} className="form-grid panel-body"><div className="form-field"><label htmlFor="recommendation-vehicle">Vehicle</label><select id="recommendation-vehicle" name="vehicleId" required><option value="">Select vehicle</option>{vehicles.map((v) => <option key={v.id} value={v.id}>{v.model?.name ?? "Volkswagen ID"} · {v.registration_no ?? v.vin}</option>)}</select></div><BranchField id="recommendation-branch" label="Recording branch" branches={branches} selectedBranchId={staff.selectedBranchId} /><div className="form-field form-span-2"><label htmlFor="recommendation-description">Recommended work</label><input id="recommendation-description" name="description" required /></div><div className="form-field"><label htmlFor="recommendation-severity">Severity</label><select id="recommendation-severity" name="severity"><option value="amber">Advisory</option><option value="red">Urgent</option><option value="safety_stop">Safety stop</option></select></div><div className="form-field"><label htmlFor="recommendation-date">Due date</label><input id="recommendation-date" name="dueDate" type="date" /></div><div className="form-field"><label htmlFor="recommendation-km">Due odometer (km)</label><input id="recommendation-km" name="dueOdometerKm" type="number" min="0" /></div><div className="form-actions form-span-2"><button className="button primary" type="submit">Record deferred work</button></div></form></section> : null}

    {managedVehicle && branches?.length ? <section className="panel operation-form vehicle-workspace" id="vehicle-controls">
      <div className="panel-header"><div><div className="panel-title">Vehicle record · {managedVehicle.model?.name ?? "Volkswagen ID"} · {managedVehicle.registration_no ?? managedVehicle.vin}</div><div className="panel-subtitle">Vehicle details, ownership and mileage history.</div></div><Link className="panel-link" href="/vehicles">Close</Link></div>
      <nav className="customer-tabs vehicle-tabs" aria-label="Vehicle record sections">
        <Link className={`customer-tab vehicle-tab ${activeVehicleTab === "profile" ? "active" : ""}`} aria-current={activeVehicleTab === "profile" ? "page" : undefined} href={`/vehicles?manage=${managedVehicle.id}&tab=profile#vehicle-controls`}><ShieldCheck /> Technical profile</Link>
        <Link className={`customer-tab vehicle-tab ${activeVehicleTab === "odometer" ? "active" : ""}`} aria-current={activeVehicleTab === "odometer" ? "page" : undefined} href={`/vehicles?manage=${managedVehicle.id}&tab=odometer#vehicle-controls`}><Gauge /> Mileage <span className="vehicle-tab-count mono">{managedVehicle.odometer_readings.length}</span></Link>
        <Link className={`customer-tab vehicle-tab ${activeVehicleTab === "ownership" ? "active" : ""}`} aria-current={activeVehicleTab === "ownership" ? "page" : undefined} href={`/vehicles?manage=${managedVehicle.id}&tab=ownership#vehicle-controls`}><UserRoundCheck /> Ownership <span className="vehicle-tab-count mono">{managedVehicle.vehicle_ownerships.length}</span></Link>
        <Link className={`customer-tab vehicle-tab ${activeVehicleTab === "service" ? "active" : ""}`} aria-current={activeVehicleTab === "service" ? "page" : undefined} href={`/vehicles?manage=${managedVehicle.id}&tab=service#vehicle-controls`}><History /> Service history <span className="vehicle-tab-count mono">{serviceHistory?.length ?? 0}</span></Link>
        {[{ id: "quotes", label: "Quotations" }, { id: "invoices", label: "Invoices & payments" }, { id: "documents", label: "Documents" }].map(tab => <Link key={tab.id} className={`customer-tab vehicle-tab ${activeVehicleTab === tab.id ? "active" : ""}`} aria-current={activeVehicleTab === tab.id ? "page" : undefined} href={`/vehicles?manage=${managedVehicle.id}&tab=${tab.id}#vehicle-controls`}>{tab.label}</Link>)}
      </nav>
      <div className="journey-actions panel-body">{managedVehicle.vehicle_ownerships.filter(o => o.valid_from <= today && (!o.valid_to || o.valid_to >= today)).map(o => o.customer ? <Link className="button compact" key={o.id} href={`/customers?manage=${o.customer.id}#customer-controls`}>{o.customer.display_name}</Link> : null)}{managedVehicle.vehicle_ownerships.find(o => o.customer && o.valid_from <= today && (!o.valid_to || o.valid_to >= today))?.customer ? <Link className="button primary" href={`/work-orders?new=1&vehicle=${managedVehicle.id}&customer=${managedVehicle.vehicle_ownerships.find(o => o.customer && o.valid_from <= today && (!o.valid_to || o.valid_to >= today))!.customer!.id}#new-work-order`}>New visit</Link> : null}</div>
      {activeVehicleTab === "profile" && (!managedVehicle.vin || !managedVehicle.registration_no) ? <details className="journey-details panel-body"><summary>Complete vehicle identity</summary><form action={completeVehicleIdentity} className="form-grid"><input type="hidden" name="vehicleId" value={managedVehicle.id}/><BranchField id="identity-branch" label="Recording branch" branches={branches} selectedBranchId={staff.selectedBranchId} value={managedVehicle.primary_branch_id}/><div className="form-field"><label htmlFor="identity-vin">VIN number</label><input id="identity-vin" name="vin" dir="ltr" defaultValue={managedVehicle.vin ?? ""} readOnly={Boolean(managedVehicle.vin)} minLength={17} maxLength={17} pattern="[A-HJ-NPR-Za-hj-npr-z0-9]{17}"/></div><div className="form-field"><label htmlFor="identity-plate">Registration number</label><input id="identity-plate" name="registrationNo" dir="ltr" defaultValue={managedVehicle.registration_no ?? ""} readOnly={Boolean(managedVehicle.registration_no)} maxLength={40}/></div><p className="field-help form-span-2">Existing identifiers are protected. Only missing details can be added.</p><div className="form-actions form-span-2"><button className="button primary" type="submit">Save</button></div></form></details> : null}
      {activeVehicleTab === "profile" ? <form action={updateVehicleProfile} className="form-grid panel-body vehicle-tab-panel"><input type="hidden" name="vehicleId" value={managedVehicle.id}/><BranchField id="profile-branch" label="Primary branch" branches={branches} selectedBranchId={staff.selectedBranchId} value={managedVehicle.primary_branch_id} /><div className="form-field"><label htmlFor="drive-unit">Drive unit</label><input id="drive-unit" name="driveUnit" defaultValue={managedVehicle.drive_unit ?? ""} placeholder="APP310 / dual motor"/></div><div className="form-field form-span-2 vehicle-identity-field"><div><label htmlFor="profile-vin">VIN number</label><span className="field-help">Permanent vehicle identity number</span></div><input className="mono" id="profile-vin" value={managedVehicle.vin ?? ""} readOnly dir="ltr" /></div><div className="form-field"><label htmlFor="profile-color">Vehicle color</label><input id="profile-color" name="color" defaultValue={managedVehicle.color ?? ""} maxLength={80} placeholder="e.g. Moonstone Grey" /></div><div className="form-field"><label htmlFor="connectivity">Connectivity</label><select id="connectivity" name="connectivityStatus" defaultValue={managedVehicle.connectivity_status}><option value="unknown">Unknown</option><option value="connected">Connected</option><option value="disconnected">Disconnected</option><option value="not_supported">Not supported</option></select></div><div className="form-field"><label htmlFor="software-version">Software version</label><input className="mono" id="software-version" name="softwareVersion" defaultValue={managedVehicle.software_version ?? ""}/></div><div className="form-field"><label htmlFor="first-registration">First registration</label><input id="first-registration" name="firstRegistrationDate" type="date" defaultValue={managedVehicle.first_registration_date ?? ""}/></div><div className="form-actions form-span-2"><button className="button primary" type="submit"><ShieldCheck/> Update vehicle profile</button></div></form> : null}
      {activeVehicleTab === "odometer" ? <div className="vehicle-tab-panel"><form action={recordOdometerReading} className="form-grid panel-body vehicle-tab-form"><input type="hidden" name="vehicleId" value={managedVehicle.id}/><BranchField id="odometer-branch" label="Recording branch" branches={branches} selectedBranchId={staff.selectedBranchId} /><div className="form-field"><label htmlFor="odometer-reading">Odometer (km)</label><input id="odometer-reading" name="readingKm" type="number" min="0" required/></div><div className="form-field"><label htmlFor="odometer-source">Source</label><select id="odometer-source" name="source" defaultValue="workshop_intake"><option value="workshop_intake">Workshop intake</option><option value="customer_reported">Customer reported</option><option value="diagnostic_scan">Diagnostic scan</option><option value="correction">Correction</option></select></div><div className="form-field"><label htmlFor="odometer-reason">Correction reason</label><input id="odometer-reason" name="correctionReason" placeholder="Required if lower than history"/></div><div className="form-actions form-span-2"><button className="button primary" type="submit"><Gauge/> Record odometer</button></div></form>{managedVehicle.odometer_readings.length ? <div className="consent-ledger vehicle-tab-ledger">{[...managedVehicle.odometer_readings].sort((a,b)=>b.recorded_at.localeCompare(a.recorded_at)).map(reading=><article key={reading.recorded_at}><div><strong>{Number(reading.reading_km).toLocaleString()} km · {reading.source}</strong><span>{reading.branch ? `${reading.branch.city} · ${reading.branch.code}` : "No branch"}{reading.correction_reason ? ` · ${reading.correction_reason}` : ""}</span></div><span>{new Date(reading.recorded_at).toLocaleDateString("en-JO")}</span></article>)}</div> : <div className="table-empty">No odometer readings recorded</div>}</div> : null}
      {activeVehicleTab === "ownership" ? <div className="vehicle-tab-panel"><form action={addVehicleOwnership} className="form-grid panel-body vehicle-tab-form"><input type="hidden" name="vehicleId" value={managedVehicle.id}/><BranchField id="ownership-branch" label="Recording branch" branches={branches} selectedBranchId={staff.selectedBranchId} /><div className="form-field"><label htmlFor="ownership-customer">Customer</label><select id="ownership-customer" name="customerId" required><option value="">Select customer</option>{customers?.map(customer=><option key={customer.id} value={customer.id}>{customer.display_name}</option>)}</select></div><div className="form-field"><label htmlFor="ownership-relationship">Relationship</label><select id="ownership-relationship" name="relationship" defaultValue="owner"><option value="owner">Owner</option><option value="driver">Driver</option><option value="fleet_manager">Fleet manager</option><option value="authorized_contact">Authorized contact</option></select></div><div className="form-field"><label htmlFor="ownership-from">Valid from</label><input id="ownership-from" name="validFrom" type="date" defaultValue={today} required/></div><label className="check-field form-span-2"><input type="checkbox" name="verified"/><span>Identity and ownership evidence verified</span></label><div className="form-actions form-span-2"><button className="button primary" type="submit"><UserRoundCheck/> Add relationship</button></div></form><div className="consent-ledger vehicle-tab-ledger">{managedVehicle.vehicle_ownerships.map(ownership=><article key={ownership.id}><div><strong>{ownership.customer?.display_name ?? "Unknown customer"} · {ownership.relationship}</strong><span>{ownership.valid_from} → {ownership.valid_to ?? "Current"} · {ownership.verified_at ? "verified" : "unverified"}</span></div>{ownership.valid_to === null ? <form action={endVehicleOwnership} className="inline-actions"><input type="hidden" name="vehicleId" value={managedVehicle.id}/><input type="hidden" name="ownershipId" value={ownership.id}/><input type="hidden" name="branchId" value={staff.selectedBranchId ?? branches[0].id}/><input name="validTo" type="date" defaultValue={today} required aria-label="Ownership end date"/><input name="reason" placeholder="Reason" required aria-label="Ownership end reason"/><button className="button compact" type="submit">End</button></form> : <span>Historical</span>}</article>)}</div></div> : null}
      {activeVehicleTab === "documents" ? <div className="panel-body"><RecordDocuments organizationId={staff.organizationId} scope={{ type: "vehicle", id: managedVehicle.id }}/></div> : null}
      {activeVehicleTab === "quotes" || activeVehicleTab === "invoices" ? <div className="panel-body"><CustomerServiceHistory organizationId={staff.organizationId} vehicleId={managedVehicle.id} view={activeVehicleTab}/></div> : null}
      {activeVehicleTab === "service" ? <div className="vehicle-tab-panel vehicle-service-history">{serviceHistory?.length ? serviceHistory.map((order, index) => <article className="vehicle-service-visit" key={order.id}>
        <div className="vehicle-service-marker"><Wrench /><span className="mono">{String(serviceHistory.length - index).padStart(2, "0")}</span></div>
        <div className="vehicle-service-card">
          <header className="vehicle-service-head"><div><div className="vehicle-service-kicker"><time dateTime={order.opened_at}>{serviceDate.format(new Date(order.opened_at))}</time><span>{order.branch?.city} · {order.branch?.code}</span></div><h3>{order.ro_number}</h3><p><CustomerConcernText value={order.customer_concern} /></p></div><StatusPill label={order.status} tone={serviceTone(order.status)} /></header>
          <dl className="vehicle-service-facts"><div><dt>Customer</dt><dd>{order.customer?.display_name ?? "Unknown customer"}</dd></div><div><dt>Intake mileage</dt><dd className="mono">{order.odometer_km === null ? "—" : `${Number(order.odometer_km).toLocaleString()} km`}</dd></div><div><dt>Closed</dt><dd><time dateTime={order.closed_at ?? undefined}>{order.closed_at ? serviceDate.format(new Date(order.closed_at)) : "Open"}</time></dd></div><div><dt>Risk</dt><dd><StatusPill label={order.risk_state} tone={order.risk_state === "quarantine" || order.risk_state === "emergency_escalation" ? "red" : order.risk_state === "restricted" ? "amber" : "gray"} /></dd></div></dl>
          <div className="vehicle-service-jobs"><div className="vehicle-service-section-title"><Wrench /><span>Services performed</span><strong className="mono">{order.jobs.length}</strong></div>{order.jobs.length ? order.jobs.map(job => <div className="vehicle-service-job" key={job.id}><div><strong>{job.description_snapshot}</strong><span>{job.operation_code || "No operation code"}{job.completed_at ? ` · ${serviceDate.format(new Date(job.completed_at))}` : ""}</span></div><StatusPill label={job.status} tone={serviceTone(job.status)} /></div>) : <p className="vehicle-service-empty">No workshop jobs recorded</p>}</div>
          {order.invoices.length ? <div className="vehicle-service-invoices"><div className="vehicle-service-section-title"><ReceiptText /><span>Invoices</span><strong className="mono">{order.invoices.length}</strong></div>{order.invoices.map(invoice => <div className="vehicle-service-invoice" key={invoice.id}><div><strong className="mono">{invoice.invoice_number ?? "Draft invoice"}</strong><span>{invoice.posted_at ? serviceDate.format(new Date(invoice.posted_at)) : "Not posted"}</span></div><div><StatusPill label={invoice.status} tone={serviceTone(invoice.status)} /><strong className="mono">{serviceMoney.format(Number(invoice.grand_total))}</strong><span className="mono">{serviceMoney.format(Number(invoice.paid_total))} paid</span></div></div>)}</div> : null}
        </div>
      </article>) : <div className="vehicle-service-empty-state"><History /><strong>No service history</strong><span>This vehicle has no linked repair orders yet.</span><Link className="button primary" href="/work-orders?new=1#new-work-order">New work order</Link></div>}</div> : null}
    </section> : null}

    <MetricStrip metrics={[
      { label: "Registered vehicles", value: String(vehicles?.length ?? 0), note: "Live registry", icon: CarFront },
      { label: "Average battery SOH", value: averageSoh === null ? "—" : `${averageSoh.toFixed(1)}%`, note: latestSoh.length ? `${latestSoh.length} measured vehicles` : "No battery tests yet", noteTone: averageSoh !== null && averageSoh >= 90 ? "good" : undefined, icon: BatteryCharging },
      { label: "Quarantined", value: String(quarantined), note: "Safety-restricted vehicles", noteTone: quarantined ? "warn" : "good", icon: CarFront },
      { label: "Open safety alerts", value: String(safetyAlerts), note: "Red or safety-stop", noteTone: safetyAlerts ? "warn" : "good", icon: BatteryCharging },
    ]} />

    {!vehicles?.length ? <EmptyState icon={CarFront} title="No vehicles registered" description={setupReady ? "Register the first vehicle and link it to its owner." : "A branch and customer are required before registering vehicles."} action={setupReady ? <Link className="button primary" href="/vehicles?new=1#new-vehicle">Register first vehicle</Link> : <Link className="button" href={branches?.length ? "/customers?new=1#new-customer" : "/branches?new=1#new-branch"}>Complete setup</Link>} /> : <section className="panel"><div className="panel-body"><RecordFilters action="/vehicles" query={query.q} facet={query.filter} label="Status" placeholder="Search VIN, registration or customer…" options={[{ value: "active", label: "Active" }, { value: "quarantine", label: "Quarantined" }, { value: "restricted", label: "Restricted" }, { value: "archived", label: "Archived" }]}/>{vehicles.length >= 1000 ? <p className="field-help">Search covers the first 1,000 loaded records.</p> : null}{!visibleVehicles.length ? <p role="status">No matching records.</p> : null}</div><div className="data-scroll"><table className="data-table"><thead><tr><th>Vehicle</th><th>VIN number</th><th>Customer</th><th>Mileage</th><th>Battery SOH</th><th>Battery</th><th>Status</th></tr></thead><tbody>{visibleVehicles.map((vehicle) => {
      const ownership = vehicle.vehicle_ownerships[0];
      const odometer = [...vehicle.odometer_readings].sort((a, b) => b.recorded_at.localeCompare(a.recorded_at))[0];
      const health = [...vehicle.battery_health_reports].sort((a, b) => b.measured_at.localeCompare(a.measured_at))[0];
      return <tr key={vehicle.id}><td><div className="cell-main"><Link href={`/vehicles?manage=${vehicle.id}#vehicle-controls`}>{vehicle.model?.name ?? "Volkswagen ID"}{vehicle.trim ? ` · ${vehicle.trim}` : ""}</Link></div><div className="cell-sub">{vehicle.registration_no ?? "No registration"}{vehicle.model_year ? ` · ${vehicle.model_year}` : ""}{vehicle.color ? ` · ${vehicle.color}` : ""} · {vehicle.connectivity_status}</div></td><td className="mono">{vehicle.vin ?? "—"}</td><td>{ownership?.customer?.display_name ?? "Unassigned"}</td><td className="mono">{odometer ? `${Number(odometer.reading_km).toLocaleString()} km` : "—"}</td><td>{health?.soh_percent !== null && health?.soh_percent !== undefined ? <StatusPill label={`${health.soh_percent}%`} tone={Number(health.soh_percent) >= 90 ? "green" : "amber"} /> : "—"}</td><td><div>{vehicle.battery_kwh ? `${vehicle.battery_kwh} kWh` : "—"}</div></td><td><StatusPill label={vehicle.status} tone={vehicle.status === "active" ? "green" : vehicle.status === "quarantine" ? "red" : "amber"} /></td></tr>;
    })}</tbody></table></div></section>}
    {recommendations?.length ? <section className="panel" style={{ marginTop: 20 }}><div className="panel-header"><div><div className="panel-title">Deferred-work register</div><div className="panel-subtitle">Organization-wide follow-up with originating branch provenance</div></div></div><div className="data-scroll"><table className="data-table"><thead><tr><th>Vehicle</th><th>Recommendation</th><th>Recorded at</th><th>Due</th><th>Status</th><th>Action</th></tr></thead><tbody>{recommendations.map((item) => <tr key={item.id}><td><div className="cell-main">{item.vehicle?.model?.name ?? "VW ID"} · {item.vehicle?.registration_no ?? item.vehicle?.vin}</div></td><td><div className="cell-main">{item.description}</div><div className="cell-sub"><StatusPill label={item.severity} tone={item.severity === "safety_stop" || item.severity === "red" ? "red" : "amber"} /></div></td><td>{item.branch?.city} · {item.branch?.code}</td><td>{item.due_date ?? "—"}{item.due_odometer_km ? ` · ${Number(item.due_odometer_km).toLocaleString()} km` : ""}</td><td><StatusPill label={item.status} tone={item.status === "completed" ? "green" : item.status === "dismissed" ? "gray" : "amber"} /></td><td>{["open", "scheduled"].includes(item.status) ? <div className="inline-actions">{item.status === "open" ? <form action={transitionRecommendation}><input type="hidden" name="recommendationId" value={item.id} /><input type="hidden" name="status" value="scheduled" /><button className="button compact" type="submit">Schedule</button></form> : null}<form action={transitionRecommendation}><input type="hidden" name="recommendationId" value={item.id} /><input type="hidden" name="status" value="completed" /><button className="button compact primary" type="submit">Complete</button></form><form action={transitionRecommendation}><input type="hidden" name="recommendationId" value={item.id} /><input type="hidden" name="status" value="dismissed" /><button className="button compact" type="submit">Dismiss</button></form></div> : "—"}</td></tr>)}</tbody></table></div></section> : null}
  </>;
}
