import { BatteryCharging, CalendarDays, CarFront, CheckCircle2, ClipboardList, FileText, LogOut, ShieldCheck, Wrench } from "lucide-react";
import { redirect } from "next/navigation";
import { RecordFeedback } from "@/components/record-feedback";
import { StatusPill } from "@/components/status-pill";
import { createClient } from "@/lib/supabase/server";
import { decideEstimate } from "./actions";
type PageQuery={created?:string;error?:string};
type PortalData={customer:{display_name:string;preferred_locale:string};vehicles:Array<{id:string;vin:string|null;registration_no:string|null;model_year:number|null;model:string|null;status:string}>;appointments:Array<{id:string;start_at:string;end_at:string;status:string;channel:string;branch:string;city:string;vehicle_id:string}>;repair_orders:Array<{id:string;ro_number:string;status:string;opened_at:string;promised_at:string|null;vehicle_id:string;branch:string;city:string}>;estimates:Array<{id:string;repair_order_id:string;version_no:number;status:string;currency:string;grand_total:number;expires_at:string|null;document_hash:string|null;lines:Array<{line_no:number;description:string;quantity:number;unit_price:number;tax_amount:number;line_total:number}>}>;invoices:Array<{id:string;invoice_number:string;status:string;currency:string;grand_total:number;paid_total:number;posted_at:string;document_hash:string|null}>;recommendations:Array<{id:string;vehicle_id:string;description:string;severity:string;status:string;due_date:string|null;due_odometer_km:number|null}>};
const dt=new Intl.DateTimeFormat("en-JO",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Amman"});const money=new Intl.NumberFormat("en-JO",{minimumFractionDigits:3,maximumFractionDigits:3});
export default async function PortalPage({searchParams}:{searchParams:Promise<PageQuery>}){const query=await searchParams;const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const [{data:identity},{data,error}]=await Promise.all([supabase.rpc("portal_identity"),supabase.rpc("portal_dashboard")]);if(error||!identity?.length||!data)redirect("/login");const portal=data as unknown as PortalData;const openEstimates=portal.estimates.filter(e=>e.status==="sent");const activeOrders=portal.repair_orders.filter(o=>!["closed","cancelled"].includes(o.status));
return <main className="portal-page"><header className="portal-header"><div className="brand"><div className="brand-mark">ID</div><div><div className="brand-name">IDstore</div><div className="brand-sub">Customer service portal</div></div></div><div className="portal-identity"><div><strong>{portal.customer.display_name}</strong><span>Secure vehicle record</span></div><a className="button compact" href="/auth/signout"><LogOut/> Sign out</a></div></header><div className="portal-content"><section className="portal-hero"><div><span>Welcome back</span><h1>Your Volkswagen ID service, without the guesswork.</h1><p>Review appointments, track workshop progress, decide estimates and keep every posted document in one authenticated record.</p></div><ShieldCheck/></section><RecordFeedback created={query.created} error={query.error}/><div className="portal-metrics"><article><CarFront/><b>{portal.vehicles.length}</b><span>Vehicles</span></article><article><Wrench/><b>{activeOrders.length}</b><span>Active services</span></article><article><FileText/><b>{openEstimates.length}</b><span>Awaiting decision</span></article><article><BatteryCharging/><b>{portal.recommendations.filter(r=>!["completed","dismissed"].includes(r.status)).length}</b><span>Recommendations</span></article></div>
{openEstimates.map(estimate=><section className="portal-estimate" key={estimate.id}><div className="portal-estimate-head"><div><span>Estimate · version {estimate.version_no}</span><h2>{money.format(estimate.grand_total)} {estimate.currency}</h2><p>{estimate.expires_at?`Valid until ${dt.format(new Date(estimate.expires_at))}`:"No expiry recorded"}</p></div><FileText/></div><div className="portal-lines">{estimate.lines.map(line=><div key={line.line_no}><span>{line.description} · {line.quantity} × {money.format(line.unit_price)}</span><strong>{money.format(line.line_total)}</strong></div>)}</div><form action={decideEstimate} className="portal-decision"><input type="hidden" name="estimateId" value={estimate.id}/><label htmlFor={`note-${estimate.id}`}>Decision note (optional)</label><textarea id={`note-${estimate.id}`} name="note" rows={2}/><div><button className="button" name="decision" value="declined" type="submit">Decline</button><button className="button primary" name="decision" value="approved" type="submit"><CheckCircle2/> Approve estimate</button></div></form></section>)}
<div className="portal-grid"><section className="panel"><div className="panel-header"><div><div className="panel-title"><CalendarDays/> Appointments</div><div className="panel-subtitle">Across all service branches</div></div></div><div className="portal-list">{portal.appointments.length?portal.appointments.map(a=><article key={a.id}><div><strong>{a.city} · {a.branch}</strong><span>{dt.format(new Date(a.start_at))}</span></div><StatusPill label={a.status} tone={a.status==="completed"?"green":"blue"}/></article>):<p className="table-empty">No appointments.</p>}</div></section><section className="panel"><div className="panel-header"><div><div className="panel-title"><ClipboardList/> Service progress</div><div className="panel-subtitle">Current and past repair orders</div></div></div><div className="portal-list">{portal.repair_orders.length?portal.repair_orders.map(o=><article key={o.id}><div><strong className="mono">{o.ro_number}</strong><span>{o.city} · opened {dt.format(new Date(o.opened_at))}</span></div><StatusPill label={o.status} tone={o.status==="closed"?"green":"blue"}/></article>):<p className="table-empty">No service history.</p>}</div></section></div>
<section className="panel"><div className="panel-header"><div><div className="panel-title"><CarFront/> Vehicles & deferred work</div><div className="panel-subtitle">Only vehicles currently linked to your account</div></div></div><div className="portal-vehicles">{portal.vehicles.map(v=><article key={v.id}><div><span>{v.model_year??""} Volkswagen</span><h3>{v.model??"ID"}</h3><code>{v.registration_no??v.vin}</code></div><div>{portal.recommendations.filter(r=>r.vehicle_id===v.id&&!["completed","dismissed"].includes(r.status)).map(r=><p key={r.id}><StatusPill label={r.severity} tone={r.severity.includes("safety")?"red":"amber"}/><span>{r.description}{r.due_date?` · due ${r.due_date}`:""}</span></p>)}</div></article>)}</div></section>
<section className="panel"><div className="panel-header"><div><div className="panel-title"><FileText/> Posted invoices</div><div className="panel-subtitle">Commercial documents visible after posting</div></div></div><div className="data-scroll"><table className="data-table"><thead><tr><th>Invoice</th><th>Posted</th><th>Total</th><th>Paid</th><th>Status</th></tr></thead><tbody>{portal.invoices.length?portal.invoices.map(i=><tr key={i.id}><td className="mono">{i.invoice_number}</td><td>{dt.format(new Date(i.posted_at))}</td><td>{money.format(i.grand_total)} {i.currency}</td><td>{money.format(i.paid_total)}</td><td><StatusPill label={i.status} tone={i.status==="paid"?"green":"amber"}/></td></tr>):<tr><td colSpan={5} className="table-empty">No posted invoices.</td></tr>}</tbody></table></div></section></div></main>}
