import { Banknote, CheckCircle2, CircleDollarSign, RotateCcw, Scale } from "lucide-react";
import { BranchField } from "@/components/branch-field";
import { EmptyState } from "@/components/empty-state";
import { MetricStrip } from "@/components/metric-strip";
import { PageHeader } from "@/components/page-header";
import { RecordFeedback } from "@/components/record-feedback";
import { StatusPill } from "@/components/status-pill";
import { getCurrentStaff } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { approveCashSession, closeCashSession, openCashSession, postCreditNote, recordRefund } from "./actions";

type PageQuery={created?:string;error?:string}; const money=new Intl.NumberFormat("en-JO",{minimumFractionDigits:3,maximumFractionDigits:3});
export default async function FinanceControlPage({searchParams}:{searchParams:Promise<PageQuery>}){
 const query=await searchParams; const staff=await getCurrentStaff(); const supabase=await createClient();
 const [{data:branches},{data:invoices},{data:lines},{data:credits},{data:payments},{data:refunds},{data:sessions,error}]=await Promise.all([
  supabase.from("branches").select("id,code,city").eq("organization_id",staff.organizationId).eq("status","active").order("city"),
  supabase.from("invoices").select("id,invoice_number,status,grand_total,paid_total,currency,customer:customers(display_name),branch:branches(code,city)").eq("organization_id",staff.organizationId).in("status",["posted","partially_paid","paid"]).order("posted_at",{ascending:false}),
  supabase.from("invoice_lines").select("id,invoice_id,line_no,description_snapshot,quantity,line_total").eq("organization_id",staff.organizationId).order("line_no"),
  supabase.from("credit_notes").select("id,credit_number,invoice_id,reason,grand_total,posted_at,invoice:invoices(invoice_number),branch:branches(code,city)").eq("organization_id",staff.organizationId).order("posted_at",{ascending:false}),
  supabase.from("payments").select("id,receipt_number,amount,currency,status,method,branch:branches(code,city),payment_allocations(invoice_id,invoice:invoices(invoice_number))").eq("organization_id",staff.organizationId).in("status",["received","partially_refunded"]).order("received_at",{ascending:false}),
  supabase.from("payment_refunds").select("id,amount,reason,status,created_at,payment:payments(receipt_number),credit_note:credit_notes(credit_number)").eq("organization_id",staff.organizationId).order("created_at",{ascending:false}),
  supabase.from("cash_sessions").select("id,register_code,opening_float,expected_close,counted_close,variance,status,opened_at,staff_user_id,branch:branches(code,city)").eq("organization_id",staff.organizationId).order("opened_at",{ascending:false}),
 ]);
 const creditable=(invoices??[]).flatMap(invoice=>(lines??[]).filter(line=>line.invoice_id===invoice.id).map(line=>({invoice,line})));
 return <><PageHeader eyebrow="Immutable finance controls" title="Credits, refunds & cash" description="Correct posted documents through linked ledgers and reconcile every physical register by branch."/><RecordFeedback created={query.created} error={query.error??(error?"Finance controls could not be loaded.":undefined)}/>
 <MetricStrip metrics={[{label:"Posted credits",value:String(credits?.length??0),note:"Traceable corrections",icon:RotateCcw},{label:"Refunds",value:String(refunds?.length??0),note:"Payment-linked",icon:CircleDollarSign},{label:"Open registers",value:String((sessions??[]).filter(s=>s.status==="open").length),note:"Cashier-owned",icon:Banknote},{label:"Variance review",value:String((sessions??[]).filter(s=>s.status==="closed"&&s.variance!==0).length),note:"Requires approval",icon:Scale}]}/>
 <div className="finance-control-grid"><section className="panel"><div className="panel-header"><div><div className="panel-title">Post credit note</div><div className="panel-subtitle">Credits cannot exceed the uncredited source quantity.</div></div></div><form action={postCreditNote} className="form-grid panel-body"><div className="form-field form-span-2"><label htmlFor="credit-line">Invoice line</label><select id="credit-line" name="invoiceLineId" required><option value="">Select posted line</option>{creditable.map(({invoice,line})=><option key={line.id} value={line.id}>{invoice.invoice_number} · line {line.line_no} · {line.description_snapshot} · qty {line.quantity}</option>)}</select></div><div className="form-field"><label htmlFor="credit-invoice">Invoice</label><select id="credit-invoice" name="invoiceId" required><option value="">Select same invoice</option>{invoices?.map(i=><option key={i.id} value={i.id}>{i.invoice_number} · {i.customer?.display_name}</option>)}</select></div><div className="form-field"><label htmlFor="credit-quantity">Quantity</label><input id="credit-quantity" name="quantity" type="number" min="0.001" step="0.001" required/></div><div className="form-field form-span-2"><label htmlFor="credit-reason">Reason</label><input id="credit-reason" name="reason" required/></div><div className="form-actions form-span-2"><button className="button primary" type="submit">Post immutable credit</button></div></form></section>
 <section className="panel"><div className="panel-header"><div><div className="panel-title">Record refund</div><div className="panel-subtitle">Must reconcile to the credited invoice allocation.</div></div></div><form action={recordRefund} className="form-grid panel-body"><div className="form-field"><label htmlFor="refund-payment">Payment</label><select id="refund-payment" name="paymentId" required><option value="">Select receipt</option>{payments?.map(p=><option key={p.id} value={p.id}>{p.receipt_number} · {money.format(p.amount)} {p.currency}</option>)}</select></div><div className="form-field"><label htmlFor="refund-credit">Credit note</label><select id="refund-credit" name="creditNoteId" required><option value="">Select credit</option>{credits?.map(c=><option key={c.id} value={c.id}>{c.credit_number} · {money.format(c.grand_total)}</option>)}</select></div><div className="form-field"><label htmlFor="refund-amount">Amount</label><input id="refund-amount" name="amount" type="number" min="0.001" step="0.001" required/></div><div className="form-field"><label htmlFor="refund-provider">Provider reference</label><input id="refund-provider" name="providerRef"/></div><div className="form-field"><label htmlFor="refund-key">Refund reference</label><input className="mono" id="refund-key" name="idempotencyKey" required/></div><div className="form-field"><label htmlFor="refund-reason">Reason</label><input id="refund-reason" name="reason" required/></div><div className="form-actions form-span-2"><button className="button dark" type="submit">Record refund</button></div></form></section></div>
 <section className="panel"><div className="panel-header"><div><div className="panel-title">Cash registers</div><div className="panel-subtitle">Opening float + cashier cash receipts − refunds = expected close.</div></div></div><form action={openCashSession} className="cash-open-form"><BranchField id="cash-branch" label="Branch" branches={branches} selectedBranchId={staff.selectedBranchId} /><input name="registerCode" placeholder="Register code" required/><input name="openingFloat" type="number" min="0" step="0.001" placeholder="Opening float" required/><button className="button primary" type="submit">Open register</button></form><div className="data-scroll"><table className="data-table"><thead><tr><th>Register</th><th>Branch</th><th>Opening</th><th>Expected</th><th>Counted</th><th>Variance</th><th>Status / action</th></tr></thead><tbody>{sessions?.length?sessions.map(s=><tr key={s.id}><td className="mono">{s.register_code}</td><td>{s.branch?.city} · {s.branch?.code}</td><td>{money.format(s.opening_float)}</td><td>{s.expected_close===null?"—":money.format(s.expected_close)}</td><td>{s.counted_close===null?"—":money.format(s.counted_close)}</td><td className={s.variance?"text-danger":""}>{s.variance===null?"—":money.format(s.variance)}</td><td>{s.status==="open"&&s.staff_user_id===staff.userId?<form action={closeCashSession} className="inline-action"><input type="hidden" name="sessionId" value={s.id}/><input name="countedClose" type="number" min="0" step="0.001" placeholder="Counted" required/><button className="button compact" type="submit">Close</button></form>:s.status==="closed"?<form action={approveCashSession} className="inline-action"><input type="hidden" name="sessionId" value={s.id}/><button className="button compact" type="submit"><CheckCircle2/> Approve</button></form>:<StatusPill label={s.status} tone="green"/>}</td></tr>):<tr><td className="table-empty" colSpan={7}>No cash sessions.</td></tr>}</tbody></table></div></section>
 {!credits?.length&&!refunds?.length?<EmptyState icon={Scale} title="No corrections recorded" description="Posted credits and reconciled refunds will appear here."/>:null}</>;
}
