-- Customer self-service requests, consent controls, payment-link requests and secured document rendering.

create table public.portal_payment_requests(
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete restrict,
  branch_id uuid not null references public.branches(id) on delete restrict, customer_id uuid not null references public.customers(id) on delete restrict,
  invoice_id uuid not null references public.invoices(id) on delete restrict, amount numeric(18,3) not null check(amount>0), currency char(3) not null,
  status text not null default 'queued' check(status in('queued','sent','paid','expired','cancelled','failed')), requested_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index portal_payment_one_open on public.portal_payment_requests(invoice_id) where status in('queued','sent');
create trigger assert_branch_organization before insert or update of organization_id,branch_id on public.portal_payment_requests for each row execute function app_private.assert_branch_organization();
create trigger touch_portal_payment_requests_updated_at before update on public.portal_payment_requests for each row execute function app_private.touch_updated_at();
alter table public.portal_payment_requests enable row level security;
create policy portal_payment_requests_select on public.portal_payment_requests for select to authenticated using(app_private.has_branch_access(organization_id,branch_id) or exists(select 1 from public.customer_accounts a where a.organization_id=portal_payment_requests.organization_id and a.customer_id=portal_payment_requests.customer_id and a.auth_user_id=auth.uid() and a.status='active'));
grant select on public.portal_payment_requests to authenticated;

create or replace function public.portal_service_options() returns jsonb language plpgsql stable security definer set search_path='' as $$ declare v_account public.customer_accounts%rowtype; begin
 select * into v_account from public.customer_accounts where auth_user_id=auth.uid() and status='active' limit 1; if not found then raise exception 'Active customer portal account not found' using errcode='42501'; end if;
 return jsonb_build_object('branches',coalesce((select jsonb_agg(jsonb_build_object('id',id,'name',display_name,'city',city,'timezone',timezone) order by city) from public.branches where organization_id=v_account.organization_id and status='active'),'[]'::jsonb),'consents',coalesce((select jsonb_agg(jsonb_build_object('purpose',purpose,'channel',channel,'state',state,'recorded_at',recorded_at) order by recorded_at desc) from public.consents where organization_id=v_account.organization_id and customer_id=v_account.customer_id),'[]'::jsonb),'payment_requests',coalesce((select jsonb_agg(jsonb_build_object('invoice_id',invoice_id,'status',status,'created_at',created_at) order by created_at desc) from public.portal_payment_requests where customer_id=v_account.customer_id),'[]'::jsonb));
end; $$;

create or replace function public.portal_request_appointment(p_branch_id uuid,p_vehicle_id uuid,p_preferred_from timestamptz,p_preferred_to timestamptz,p_duration_minutes integer,p_service_mode text,p_transport_mode text,p_notes text)
returns public.appointment_waitlist language plpgsql security definer set search_path='' as $$ declare v_account public.customer_accounts%rowtype; v_row public.appointment_waitlist%rowtype; begin
 select * into v_account from public.customer_accounts where auth_user_id=auth.uid() and status='active' limit 1; if not found then raise exception 'Active customer portal account not found' using errcode='42501'; end if;
 if not exists(select 1 from public.branches where id=p_branch_id and organization_id=v_account.organization_id and status='active') or not exists(select 1 from public.vehicle_ownerships where organization_id=v_account.organization_id and customer_id=v_account.customer_id and vehicle_id=p_vehicle_id and valid_from<=current_date and(valid_to is null or valid_to>=current_date)) then raise exception 'Branch or vehicle is unavailable' using errcode='42501'; end if;
 if p_preferred_from<now() or p_preferred_to<=p_preferred_from or p_duration_minutes not between 15 and 480 or p_service_mode not in('workshop','mobile') or p_transport_mode not in('customer_dropoff','wait_on_site','pickup_return','loan_vehicle') then raise exception 'Appointment request is invalid' using errcode='22023'; end if;
 insert into public.appointment_waitlist(organization_id,branch_id,customer_id,vehicle_id,preferred_from,preferred_to,duration_minutes,service_mode,transport_mode,priority,notes,created_by) values(v_account.organization_id,p_branch_id,v_account.customer_id,p_vehicle_id,p_preferred_from,p_preferred_to,p_duration_minutes,p_service_mode,p_transport_mode,3,nullif(trim(p_notes),''),auth.uid()) returning * into v_row;
 insert into integration.outbox_events(organization_id,event_type,aggregate_type,aggregate_id,payload,idempotency_key) values(v_account.organization_id,'appointment.requested','appointment_waitlist',v_row.id,jsonb_build_object('waitlist_id',v_row.id,'branch_id',p_branch_id,'customer_id',v_account.customer_id),'portal.appointment:'||v_row.id::text); return v_row;
end; $$;

create or replace function public.portal_update_consent(p_purpose text,p_channel text,p_state text)
returns public.consents language plpgsql security definer set search_path='' as $$ declare v_account public.customer_accounts%rowtype; v_row public.consents%rowtype; begin
 select * into v_account from public.customer_accounts where auth_user_id=auth.uid() and status='active' limit 1; if not found then raise exception 'Active customer portal account not found' using errcode='42501'; end if;
 if nullif(trim(p_purpose),'') is null or p_channel not in('email','sms','whatsapp','push','phone') or p_state not in('granted','withdrawn') then raise exception 'Consent choice is invalid' using errcode='22023'; end if;
 insert into public.consents(organization_id,customer_id,purpose,channel,state,policy_version,source,recorded_by) values(v_account.organization_id,v_account.customer_id,trim(p_purpose),p_channel,p_state,'2026-09','customer_portal',auth.uid()) returning * into v_row;
 insert into audit.events(organization_id,actor_id,action,entity_type,entity_id,metadata) values(v_account.organization_id,auth.uid(),'customer.consent_'||p_state,'customer',v_account.customer_id,jsonb_build_object('purpose',p_purpose,'channel',p_channel,'source','portal')); return v_row;
end; $$;

create or replace function public.portal_request_payment_link(p_invoice_id uuid)
returns public.portal_payment_requests language plpgsql security definer set search_path='' as $$ declare v_account public.customer_accounts%rowtype; v_invoice public.invoices%rowtype; v_row public.portal_payment_requests%rowtype; v_due numeric; begin
 select * into v_account from public.customer_accounts where auth_user_id=auth.uid() and status='active' limit 1; if not found then raise exception 'Active customer portal account not found' using errcode='42501'; end if;
 select * into strict v_invoice from public.invoices where id=p_invoice_id and organization_id=v_account.organization_id and customer_id=v_account.customer_id and status in('posted','partially_paid') for update; v_due:=v_invoice.grand_total-v_invoice.paid_total; if v_due<=0 then raise exception 'Invoice has no payable balance' using errcode='22023'; end if;
 insert into public.portal_payment_requests(organization_id,branch_id,customer_id,invoice_id,amount,currency,requested_by) values(v_invoice.organization_id,v_invoice.branch_id,v_invoice.customer_id,v_invoice.id,v_due,v_invoice.currency,auth.uid()) on conflict(invoice_id) where status in('queued','sent') do update set amount=excluded.amount,updated_at=now() returning * into v_row;
 insert into integration.outbox_events(organization_id,event_type,aggregate_type,aggregate_id,payload,idempotency_key) values(v_invoice.organization_id,'payment_link.requested','portal_payment_request',v_row.id,jsonb_build_object('request_id',v_row.id,'invoice_id',v_invoice.id,'amount',v_due,'currency',v_invoice.currency),'payment-link:'||v_row.id::text) on conflict(organization_id,idempotency_key) do nothing; return v_row;
end; $$;

create or replace function public.portal_document(p_document_type text,p_document_id uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$ declare v_account public.customer_accounts%rowtype; v_result jsonb; begin
 select * into v_account from public.customer_accounts where auth_user_id=auth.uid() and status='active' limit 1; if not found then raise exception 'Active customer portal account not found' using errcode='42501'; end if;
 if p_document_type='invoice' then select jsonb_build_object('type','invoice','number',i.invoice_number,'status',i.status,'currency',i.currency,'subtotal',i.subtotal,'discount',i.discount_total,'tax',i.tax_total,'total',i.grand_total,'paid',i.paid_total,'hash',i.document_hash,'issued_at',i.posted_at,'customer',c.display_name,'lines',(select coalesce(jsonb_agg(jsonb_build_object('description',l.description_snapshot,'quantity',l.quantity,'unit_price',l.unit_price,'tax',l.tax_amount,'total',l.line_total) order by l.line_no),'[]'::jsonb) from public.invoice_lines l where l.invoice_id=i.id)) into v_result from public.invoices i join public.customers c on c.id=i.customer_id where i.id=p_document_id and i.organization_id=v_account.organization_id and i.customer_id=v_account.customer_id and i.status<>'draft';
 elsif p_document_type='estimate' then select jsonb_build_object('type','estimate','number','EST-'||e.version_no,'status',e.status,'currency',e.currency,'subtotal',e.subtotal,'discount',e.discount_total,'tax',e.tax_total,'total',e.grand_total,'hash',e.document_hash,'issued_at',e.sent_at,'customer',c.display_name,'lines',(select coalesce(jsonb_agg(jsonb_build_object('description',l.description_snapshot,'quantity',l.quantity,'unit_price',l.unit_price,'tax',l.tax_amount,'total',l.line_total) order by l.line_no),'[]'::jsonb) from public.estimate_lines l where l.estimate_version_id=e.id)) into v_result from public.estimate_versions e join public.repair_orders r on r.id=e.repair_order_id join public.customers c on c.id=r.customer_id where e.id=p_document_id and e.organization_id=v_account.organization_id and r.customer_id=v_account.customer_id and e.status<>'draft'; else raise exception 'Document type is invalid' using errcode='22023'; end if;
 if v_result is null then raise exception 'Document not found' using errcode='P0002'; end if; return v_result;
end; $$;

do $$ declare r regprocedure; begin foreach r in array array['public.portal_service_options()'::regprocedure,'public.portal_request_appointment(uuid,uuid,timestamptz,timestamptz,integer,text,text,text)'::regprocedure,'public.portal_update_consent(text,text,text)'::regprocedure,'public.portal_request_payment_link(uuid)'::regprocedure,'public.portal_document(text,uuid)'::regprocedure] loop execute format('revoke all on function %s from public,anon,authenticated',r); execute format('grant execute on function %s to authenticated',r); end loop; end $$;
